build: 
	cd .. && cd frontend && npm run build && cd .. && cd backend

serve:
	cd .. && cd frontend && npm run build && cd .. && cd backend && fastapi dev main.py --host 0.0.0.0

# steps
# go into frontend
# npm run build
# npm run move   # that moves the built files to /dbay_control/
# 

# run "pyinstaller main.spec"