[project]
name = "dbaybackend"
version = "0.1.2"
description = "backend server for the Device Bay electronics system"
requires-python = ">=3.11,<3.14"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "psutil>=6.1.0",
    "pyinstaller>=6.11.1",
]



